import express from "express";
import cargoRoutes from "./routes/cargoRoutes";
import anoLetivoRoutes from "./routes/anoLetivoRoutes";
import assiduidadeRoutes from "./routes/assiduidadeRoutes";
import classeRoutes from "./routes/classeRoutes";
import classedisciplinaRoutes from "./routes/classeDisciplinaRoutes";
import contatoRoutes from "./routes/contatoRoutes";
import cursoRoutes from "./routes/cursoRoutes";
import disciplinaRoutes from "./routes/disciplinaRoutes";
import documentoRoutes from "./routes/documentoRoutes";
import enderecoRoutes from "./routes/enderecoRoutes";
import epocaRoutes from "./routes/epocaRoutes";
import epocaturmaRoutes from "./routes/epocaturmaRoutes";
import funcionarioRoutes from "./routes/funcionarioRoutes";
import horarioRoutes from "./routes/horarioRoutes";
import matriculaRoutes from "./routes/matriculasRoutes";
import municipioRoutes from "./routes/municipioRoutes";
import pagamentoRoutes from "./routes/pagamentoRoutes";
import permissaoRoutes from "./routes/permissaoRoutes";
import pessoaRoutes from "./routes/pessoaRoutes";
import professorRoutes from "./routes/professorRoutes";
import professorDisciplinaRoutes from "./routes/professorDisciplinaRoutes";
import professorTurmaAssRoutes from "./routes/professorTurmaAssRoutes";
import provasRoutes from "./routes/provasRoutes";
import salaRoutes from "./routes/salaRoutes";
import provinciaRoutes from "./routes/provinciaRoutes";
import authRoutes from "./routes/authRoutes";
import servicoRoutes from "./routes/servicoRoutes";
import tipoProvaRoutes from "./routes/tipoProvaRoutes";
import tipoUsuarioRoutes from "./routes/tipoUsuarioRoutes";
import turnoRoutes from "./routes/turnoRoutes";

const app = express();
app.use(express.json());

// Usar as rotas
app.use("/cargos", cargoRoutes);
app.use("/anoletivos", anoLetivoRoutes);
app.use("/assiduidade", assiduidadeRoutes);
app.use("/classes", classeRoutes);
app.use("/classedisciplinas", classedisciplinaRoutes);
app.use("/contatos", contatoRoutes);
app.use("/cursos", cursoRoutes);
app.use("/disciplinas", disciplinaRoutes);
app.use("/documentos", documentoRoutes);
app.use("/enderecos", enderecoRoutes);
app.use("/epocas", epocaRoutes);
app.use("/epocaturmas", epocaturmaRoutes);
app.use("/funcionarios", funcionarioRoutes);
app.use("/horarios", horarioRoutes);
app.use("/matriculas", matriculaRoutes);
app.use("/municipios", municipioRoutes);
app.use("/pagamentos", pagamentoRoutes);
app.use("/permissoes", permissaoRoutes);
app.use("/pessoas", pessoaRoutes);
app.use("/professores", professorRoutes);
app.use("/professoredisciplinas", professorDisciplinaRoutes);
app.use("/professorturmaass", professorTurmaAssRoutes);
app.use("/provas", provasRoutes);
app.use("/salas", salaRoutes);
app.use("/auth", authRoutes);
app.use("/servico", servicoRoutes);
app.use("/tipoprovas", tipoProvaRoutes);
app.use("/provincias", provinciaRoutes);
app.use("/tipousuarios", tipoUsuarioRoutes);
app.use("/turnos", turnoRoutes);

export default app;
